### ISSUE TITLE
Indicate minimum Node version for ro-crate-js

### ISSUE THREAD

**Issue by stain** [Language-Research-Technology/ro-crate-js#5]
I've tried to use `ro-crate-html` but got an error I suspect is due to old Node version:

```
(ro-crate) stain@xena11:~/src/ro-crate$ rochtml
/home/stain/miniconda3/envs/ro-crate/lib/node_modules/ro-crate-html/node_modules/ro-crate/lib/rocrate.js:39
  static defaults = defaults;
                  ^

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/stain/miniconda3/envs/ro-crate/lib/node_modules/ro-crate-html/node_modules/ro-crate/index.js:1:81)

(ro-crate) stain@xena11:~$ node --version
v8.12.0
```

Would you add to both `ro-crate-js` and `ro-crate-html` README some hints about node version that is minimally required? Not sure if NPM also needs to be told.

**Comment by alvinsw** [comment]
Thank you for letting us know about this issue. Yes, the library has only been tested on Node 16 and 18 at the moment. It uses a lot of the new ES constructs. I think the minimum Node version is 16.11.0, but we have not tested it with older Node. Note that Node 18 is LTS and Node 19 is current. I will add the minimum Node version requirement into the next release.
